# Intro to Scientific Computing with Python

In this notebook, we will explore two of the most important libraries in Python for scientific computing: NumPy and Matplotlib. 

## NumPy

NumPy is the fundamental scientific computing package in Python. It is a Python library that provides support for large multidimensional arrays and matrices along with a collection of mathematical functions to operate on these arrays.

### Key Features of NumPy

- **ndarray (N-dimensional array)**: NumPy's core data structure, providing fast and memory-efficient arrays.
- **Mathematical Functions**: Operations on arrays (element-wise), linear algebra, statistics, and more.
- **Broadcasting**: A powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.
- **Vectorization**: Expressing operations as occurring on entire arrays rather than their individual elements, leading to faster execution.

### Installation

NumPy is included in the Anaconda distribution, so you don't need to install it separately. If you are using a different Python distribution, you can install NumPy using pip:

```bash
pip install numpy
```
It is then ready to use just like any other Python library.

### Working with NumPy Arrays

Numpy's primary data structure is the `ndarray`, which is a multidimensional array of fixed-size items. With NumPy, it is easy to perform mathematical operations on arrays, making it a powerful tool for scientific computing.

To create a NumPy array, you can use the `np.array()` function. Let's create a simple 1D array:

```python
import numpy as np

# Create a 1D NumPy array
arr = np.array([1, 2, 3, 4, 5])
print(arr)

#Create a 2D NumPy array
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)
```
Within NumPy, several helper functions are available to create arrays in specific patterns:
- `np.zeros()`: Create an array of zeros.
- `np.ones()`: Create an array of ones.
- `np.arange()`: Create an array with a range of values.
- `np.linspace()`: Create an array with a specified number of elements, evenly spaced between two values.
- `np.random.rand()`: Create an array of random values between 0 and 1.

Each of these functions has several parameters that allow you to customize the output array as needed. A full list of functions and their parameters can be found in the [NumPy documentation](https://numpy.org/doc/stable/reference/routines.html).

Example:
```python
# Creating an array of zeros
zeros_arr = np.zeros((3, 4))
print("Zeros Array:\n", zeros_arr)

# Creating an array of ones
ones_arr = np.ones((2, 3))
print("Ones Array:\n", ones_arr)

# Creating an array with a range of values
range_arr = np.arange(10, 20, 2)
print("Range Array:", range_arr)

# Creating an array of linearly spaced values
linspace_arr = np.linspace(0, 1, 5)
print("Linspace Array:", linspace_arr)
```

### Array Operations

NumPy provides a wide range of mathematical functions that can be applied to arrays. These functions can be used to perform operations on arrays, such as element-wise addition, subtraction, multiplication, division, and more.

**Element-wise Operations**
```python   
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

# Element-wise addition
print("Addition:", arr1 + arr2)

# Element-wise multiplication
print("Multiplication:", arr1 * arr2)
```

**Mathematical Functions**
```python
# Applying square root element-wise
sqrt_arr = np.sqrt(arr1)
print("Square root:", sqrt_arr)

# Applying sine function element-wise
sin_arr = np.sin(arr1)
print("Sine of elements:", sin_arr)
```

**Universal Functions (ufuncs)**
NumPy has built-in universal functions (ufuncs) that allow you to perform operations on arrays, like calculating the sum or product across dimensions, or applying a custom function to each element.
```python
# Sum of all elements
total_sum = np.sum(arr1)
print("Sum of Elements:", total_sum)

# Sum along axis 0 (columns for a 2D array)
arr2d = np.array([[1, 2, 3], [4, 5, 6]])
sum_cols = np.sum(arr2d, axis=0)
print("Sum Along Columns:\n", sum_cols)

# Product of all elements
prod_total = np.prod(arr2d)
print("Product of Elements:", prod_total)
```

**Array Indexing and Slicing**
NumPy arrays can be indexed and sliced just like Python Lists.
```python
arr = np.array([10, 20, 30, 40, 50])

# Accessing the first element
print("First element:", arr[0])

# Slicing a subarray
print("Sliced array:", arr[1:4])

# Boolean indexing to select elements greater than 30
print("Elements greater than 30:", arr[arr > 30])
```
**Broadcasting**
Broadcasting is a powerful mechanism that allows NumPy to work with arrays of different shapes when performing arithmetic operations.
```python
#Broadcasting with a scalar value
arr = np.array([1, 2, 3])
result = arr + 10
print("Broadcasting with scalar:", result)

#Broadcasting with Two Arrays
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr2 = np.array([10, 20, 30])
result = arr1 + arr2
print("Broadcasting with two arrays:\n", result)
```

**Linear Algebra Operations**
NumPy provides a wide range of linear algebra functions, such as matrix multiplication, matrix inversion, eigenvalues, and more.
```python
# Matrix Multiplication
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
mat_prod = np.dot(mat1, mat2)
print("Matrix Multiplication:\n", mat_prod)

# Matrix Inversion
mat_inv = np.linalg.inv(mat1)
print("Matrix Inversion:\n", mat_inv)
```
**Reshaping Arrays**
You can change the shape of an array using the `reshape()` function. This can be useful when you want to change a 1D array into a 2D array or vice versa.
```python
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Reshape the 1D array into a 3x3 2D array
reshaped_arr = arr.reshape(3, 3)
print("Reshaped Array:\n", reshaped_arr)
# Output:
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]
```

Additionally, NumPy provides several other functions for array manipulation, such as `flatten()`, `ravel()`, `transpose()`, `stack()`, `split()`, and more. These functions allow you to perform a wide range of operations on arrays, such as flattening, transposing, stacking, and splitting arrays.

### Understanding NumPy Axes

The concept of axes is important when working with NumPy arrays. Many operations in NumPy allow you to specify an axis along which the operation should be performed. Axes can take a little time to get used to, but they are essential for working with multi-dimensional arrays. 

#### Basics

In Numpy, Axes are numbered starting from 0 as follows:
- **1D array**: Axis 0
- **2D array**: Axis 0 (rows), Axis 1 (columns)
- **3D array**: Axis 0 (depth), Axis 1 (rows), Axis 2 (columns)

This concept is essential when you are working with multi-dimensional arrays and performing operations like sum, mean, etc., along a specific axis.

#### Array Shape and Axes

The **Shape** of an array tells you the number of elements along each axis. For example:

- A 1D array with 5 elements has a shape of (5,)
- A 2D array with 2 rows and 3 columns has a shape of (2, 3)
- A 3D array with 2 depth, 3 rows, and 4 columns has a shape of (2, 3, 4)

The **Shape** of an array can be accessed using the `shape` attribute of the array.

```python

arr = np.array([[1, 2, 3], [4, 5, 6]])
print("Shape of the array:", arr.shape)

``` 







# Data Visualization with Matplotlib

Matplotlib is a comprehensive library for creating static, animated, and interactive visualizations in Python. It is built on NumPy arrays and designed to work with the broader SciPy stack.

### Key Features of Matplotlib

- **Simple and Consistent API**: Matplotlib has a simple and consistent API that makes it easy to create a wide range of plots.
- **Customizable**: You can customize every aspect of a plot, including colors, labels, fonts, and more.
- **Wide Range of Plots**: Matplotlib supports a wide range of plots, including line plots, scatter plots, bar plots, histograms, pie charts, and more.
- **Publication Quality**: Matplotlib produces high-quality plots that are suitable for publication.

## Sample Plot

In this example, we will be plotting sin and cos functions using Matplotlib.

The first step is to import the required libraries for matplotlib.

In [ ]:
import numpy as np
import matplotlib.pyplot as plt

Once we have imported the libraries, we need data to plot. This can be done via Numpy as shown below. 

In [ ]:
# Create an array of 100 evenly spaced points between 0 and 2π
x = np.linspace(0, 2 * np.pi, 100)
# Compute the sin of each x value
y_sin = np.sin(x)
# Same for cos
y_cos = np.cos(x)

Once we have the data, we can at last use matplot lib. There are several different ways to plot, so keep this in mind, but I will be using the most straightforward method, which is the `plt.plot()` method. 


In [ ]:
plt.figure(figsize=(8, 4))  # Optional: set the figure size

# Plot the sine wave
plt.plot(x, y_sin, label='sin(x)', color='blue', linewidth=2)
plt.plot(x, y_cos, label='sin(x)', color='blue', linewidth=2)

# Add a title and axis labels
plt.title('Sine Wave')
plt.xlabel('x')
plt.ylabel('trig(x)')

# Add a legend to the plot
plt.legend()

# Display the plot
plt.show()